env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  consistent-return: off
  default-case: off
  max-len: off
  no-plusplus: off
  no-restricted-syntax: off
  import/no-unresolved: off
  import/extensions: off
